POST http://localhost:3000/campaigns

{
  "Name": "campaign",
	"Content": "Campaign test",
	"emails": ["campaign@test.com"]
}

################################
GET http://localhost:3000/campaigns/cthp6kjsc480g33h0b80

